// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC20xXpWmvLSCddNlzxalSFffIdbcX5cV0',
    appId: '1:481861301714:web:80a74e1da81b3b291a440b',
    messagingSenderId: '481861301714',
    projectId: 'polar-glow-backend',
    authDomain: 'polar-glow-backend.firebaseapp.com',
    storageBucket: 'polar-glow-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrVamC6_aUo611d4d-X1UPWsKFS6L-sWo',
    appId: '1:481861301714:android:ee027400e36675491a440b',
    messagingSenderId: '481861301714',
    projectId: 'polar-glow-backend',
    storageBucket: 'polar-glow-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHrEKRyRlPFRTHvw33WiL8T6RpGcePEA0',
    appId: '1:481861301714:ios:01ed06d74cf827181a440b',
    messagingSenderId: '481861301714',
    projectId: 'polar-glow-backend',
    storageBucket: 'polar-glow-backend.firebasestorage.app',
    iosClientId: '481861301714-j1gp8miaaijim69t9ukmogr482bllqjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.polarGlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHrEKRyRlPFRTHvw33WiL8T6RpGcePEA0',
    appId: '1:481861301714:ios:01ed06d74cf827181a440b',
    messagingSenderId: '481861301714',
    projectId: 'polar-glow-backend',
    storageBucket: 'polar-glow-backend.firebasestorage.app',
    iosClientId: '481861301714-j1gp8miaaijim69t9ukmogr482bllqjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.polarGlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfmFTDpHl1yfLu1tPdqx3lqVVh6ZYu6vU',
    appId: '1:481861301714:web:ad31b6b12e867cbd1a440b',
    messagingSenderId: '481861301714',
    projectId: 'polar-glow-backend',
    authDomain: 'polar-glow-backend.firebaseapp.com',
    storageBucket: 'polar-glow-backend.firebasestorage.app',
  );
}
